apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kata-dictionary
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: kata-dictionary
  namespaceSelector:
    matchNames:
      - dev
  endpoints:
    - port: http
      path: /
      interval: 15s
