name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-secure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install bandit checkov

    - name: Run tests
      run: pytest app/tests.py -v

    - name: Security scan (Bandit)
      run: bandit -r app/ --configfile bandit.yaml

    - name: IaC scan (Checkov)
      run: checkov -d .

  docker-build-and-scan:
    runs-on: ubuntu-latest
    needs: build-test-secure
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/kata-dictionary:latest .

    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/${{ github.repository }}/kata-dictionary:latest
        severity: CRITICAL,HIGH

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ github.repository }}/kata-dictionary:latest
