heck failure on line 1 in .github/workflows/ci.yml


GitHub Actions
/ .github/workflows/ci.yml
Invalid workflow file

(Line: 1, Col: 3): Unexpected value 'docker-build-and-scan', (Line: 1, Col: 3): Required property is missing: jobs
    runs-on: ubuntu-latest
    needs: build-test-secure
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo name
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.REPO_LC }}/kata-dictionary:latest .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: ghcr.io/${{ env.REPO_LC }}/kata-dictionary:latest

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ env.REPO_LC }}/kata-dictionary:latest
