  docker-build-and-scan:
    runs-on: ubuntu-latest
    needs: build-test-secure
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/kata-devops-dictionary:latest .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/kata-devops-dictionary:latest

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/kata-devops-dictionary:latest
